# Generated by Django 3.1.6 on 2021-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
