# Generated by Django 3.1.6 on 2021-02-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_homepage_hero_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_btn_link',
            field=models.ForeignKey(blank=True, help_text='Internal page link to send the user to article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_btn_text',
            field=models.CharField(blank=True, default='Read more', help_text='Call-To-Action Buttton Text', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle following the maintitle in the hero section', max_length=200),
        ),
    ]
